server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVER_ADDRESS}/${MYSQL_DATABASE_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # 최대 파일 크기 설정
      max-request-size: 10MB   # 최대 요청 크기 설정

  profiles:
    include:
      - jwt
      - oauth

  phone-authcode-expiration-millis: ${PHONE_AUTHCODE_EXPIRATION}

  # 장바구니 유효기간
  cart-expiration-millis: ${CART_EXPIRATION}
  
  # Redis 카카오페이 tid 유효 기간
  kakaopay-tid-expiration-millis: ${KAKAOPAY_TID_EXPIRATION}

  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=admin
redis:
  host: ${REDIS_SERVER_ADDRESS}
  port: ${REDIS_SERVER_PORT}

#SMS 인증을 위한 Api Key
coolsms:
  apiKey: ${COOLSMS_API_KEY}
  apiSecret: ${COOLSMS_SECRET_KEY}
  senderNumber: ${COOLSMS_SENDER_NUMBER}

#전화번호 양방향 암호화 대칭키
symmetric:
  key: ${SYMMETRIC_KEY}
  salt: ${SYMMETRIC_SALT}

#로컬 파일업로드 경로
file:
  upload-dir: ${FILE_UPLOAD_DIR}

# 카카오페이 Secret Key
pay:
  secret-key: ${KAKAOPAY_SECRET_KEY}

# FCM Secret Key 파일 경로
firebase:
  path: ${FCM_SECRET_KEY_PATH}

# Redirect URL
redirectURL : ${REDIRECT_URL}

aws:
  region: ${AWS_REGION}  # AWS S3 리전 설정 (서울 리전 예시)
  credentials:
    accessKey: ${AWS_ACCESS_KEY}  # 실제 AWS 액세스 키로 대체
    secretKey: ${AWS_SECRET_KEY}  # 실제 AWS 시크릿 키로 대체
  s3:
    bucket: ${AWS_S3_BUCKET}  # 실제 S3 버킷 이름으로 대체
